# Generated by Django 5.2.8 on 2025-12-09 16:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('home_shots_on_goal', models.IntegerField(blank=True, null=True)),
                ('home_shots_off_goal', models.IntegerField(blank=True, null=True)),
                ('home_total_shots', models.IntegerField(blank=True, null=True)),
                ('home_shots_inside_box', models.IntegerField(blank=True, null=True)),
                ('home_shots_outside_box', models.IntegerField(blank=True, null=True)),
                ('home_blocked_shots', models.IntegerField(blank=True, null=True)),
                ('home_fouls', models.IntegerField(blank=True, null=True)),
                ('home_corners', models.IntegerField(blank=True, null=True)),
                ('home_offsides', models.IntegerField(blank=True, null=True)),
                ('home_possession', models.CharField(blank=True, max_length=10, null=True)),
                ('home_yellow_cards', models.IntegerField(blank=True, null=True)),
                ('home_red_cards', models.IntegerField(blank=True, null=True)),
                ('home_passes_total', models.IntegerField(blank=True, null=True)),
                ('home_passes_accurate', models.IntegerField(blank=True, null=True)),
                ('home_goalkeeper_saves', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('away_shots_on_goal', models.IntegerField(blank=True, null=True)),
                ('away_shots_off_goal', models.IntegerField(blank=True, null=True)),
                ('away_total_shots', models.IntegerField(blank=True, null=True)),
                ('away_blocked_shots', models.IntegerField(blank=True, null=True)),
                ('away_shots_inside_box', models.IntegerField(blank=True, null=True)),
                ('away_shots_outside_box', models.IntegerField(blank=True, null=True)),
                ('away_fouls', models.IntegerField(blank=True, null=True)),
                ('away_corners', models.IntegerField(blank=True, null=True)),
                ('away_offsides', models.IntegerField(blank=True, null=True)),
                ('away_possession', models.CharField(blank=True, max_length=10, null=True)),
                ('away_yellow_cards', models.IntegerField(blank=True, null=True)),
                ('away_red_cards', models.IntegerField(blank=True, null=True)),
                ('away_passes_total', models.IntegerField(blank=True, null=True)),
                ('away_passes_accurate', models.IntegerField(blank=True, null=True)),
                ('away_goalkeeper_saves', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MatchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_score', models.FloatField()),
                ('hype_score', models.FloatField()),
                ('tactical_score', models.FloatField()),
                ('aggression_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='SportApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.league')),
            ],
            options={
                'unique_together': {('league', 'year')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='SportApp.season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='SportApp.league')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='SportApp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='SportApp.team'),
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_api_id', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.team')),
            ],
            options={
                'ordering': ['-goals'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
                ('played', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goals_diff', models.IntegerField(default=0)),
                ('home_played', models.IntegerField(default=0)),
                ('home_win', models.IntegerField(default=0)),
                ('home_draw', models.IntegerField(default=0)),
                ('home_lose', models.IntegerField(default=0)),
                ('home_goals_for', models.IntegerField(default=0)),
                ('home_goals_against', models.IntegerField(default=0)),
                ('away_played', models.IntegerField(default=0)),
                ('away_win', models.IntegerField(default=0)),
                ('away_draw', models.IntegerField(default=0)),
                ('away_lose', models.IntegerField(default=0)),
                ('away_goals_for', models.IntegerField(default=0)),
                ('away_goals_against', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'team')},
            },
        ),
        migrations.CreateModel(
            name='MatchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='SportApp.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'match')},
            },
        ),
    ]
